export const textGlobal = {
  PLEASE_INPUT_PHONE_PASSWORD: 'Vui lòng nhập số điện thoại và mật khẩu',
  INPUT_PHONE: 'Nhập số điện thoại',
  PLEASE_INPUT_PHONE: 'Vui lòng nhập số điện thoại',
  PLEASE_INPUT_CMND: 'Vui lòng nhập số CMND',
  INPUT_PASSWORD: 'Nhập mật khẩu',
  SIGN_IN: 'Đăng nhập',
  SIGN_UP: 'Đăng ký',
  SIGN_UP_NOW: 'Đăng ký ngay',
  SIGN_IN_NOW: 'Đăng nhập ngay',
  OR: 'Hoặc',
  DONT_HAVE_ACCOUNT: 'Chưa có tài khoản?',
  BACK_TO_HOME: 'Về trang chủ',
  FORGOT_PASSWORD: 'Quên mật khẩu',
  INPUT_OTP: 'Nhập mã OTP',
  RESEND_OTP: 'Gửi lại mã OTP',
  CCCD: 'CCCD',
  CMND: 'CMND',
  PLEASE_SCAN_QR_CODE_ON_CCCD: 'Vui lòng quét mã QR trên CCCD',
  ALDREADY_HAVE_ACCOUNT: 'Đã có tài khoản?',
  CAMERA_NOT_AVAILABLE: 'Camera không khả dụng',
  FULL_NAME: 'Họ và tên',
  GENDER: 'Giới tính',
  DOB: 'Ngày sinh',
  ADDRESS: 'Địa chỉ',
  DATE_OF_CREATE_CCCD: 'Ngày cấp CCCD',
  INTRO_HEADER_TEXT: 'Xin chào Bạn!',
  INTRO_SUB_HEADER_TEXT: 'Hãy đăng nhập để có trải nghiệm tốt nhất',
  BOOKING_NOW: 'Đặt Lịch Khám Bệnh Ngay!',
  PACKING_SERVICE: 'Gói dịch vụ',
  SEE_MORE: 'Xem thêm',
  PACKAGES: 'Các gói dịch vụ',
  COMMUNITY_ASK_SUB: 'Cộng đồng hỏi đáp',
  TELE_HEALTH: 'Tư vấn sức khoẻ từ xa',
  GUIDE_BOOKING_APPOINTMENT: 'Hướng dẫn đặt khám',
  LABORATORY_AT_HOME: 'Xét nghiệm tại nhà',
  HOT_LINE_CONNECT: 'Liên hệ Hotline',
  NEWS_SPECIAL: 'Tin tức nổi bật',
  HOME: 'Trang chủ',
  HELLO: 'Xin chào,',
  ID: 'Mã số',
  BOOKING_INFORMATION: 'Thông tin khám bệnh',
  CASH_FEE: 'Thu phí',
  BHYT: 'BHYT',
  EXAMINATION_TYPE: 'Hình thức khám',
  PLEASE_SELECT_SPECIALTY: 'Vui lòng chọn chuyên khoa phù hợp với bạn',
  CHOOSE_SPECIALTY: 'Chọn chuyên khoa',
  CHOOSE_DOCTOR: 'Chọn bác sĩ',
  CHOOSE_DATE_APPOINTMENT: 'Chọn ngày khám',
  NEXT: 'Tiếp tục',
  BACK: 'Quay lại',
  PLEASE_CONFIRM_YOUR_INFORMATION_APPOINTMENT:
    'Vui lòng xác nhận thông tin chi tiết lịch hẹn khám của bạn!',
  INFORMATION_OF_PATIENT: 'Thông tin bệnh nhân',
  INFORMATION_OF_SERVICE_APPOINTMENT: 'Thông tin dịch vụ khám',
  HOSPITAL_NAME: 'Bệnh viện Bình Dân',
  DATE_OF_APPOINTMENT: 'Ngày hẹn khám bệnh',
  HOT_LINE: 'Hotline',
  TOTAL: 'Tổng Cộng:',
  PAY_BEFORE: 'Thanh toán trước',
  CHOOSE_ICON_QR_CODE: 'Chọn biểu tượng mã QR để quét mã QR',
  SIGN_UP_SUCCESSFULL: 'Đăng ký thành công',
  APPOINTMENT_SUCCESSFULL: 'Đặt lịch thành công',
  SPECIALTY: 'Chuyên khoa',
};
